In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

print("All libraries imported successfully!")

All libraries imported successfully!

In [2]:
import os

raw_path = "../data/raw"

print(os.listdir(raw_path))

['title.basics.tsv.gz', 'title.ratings.tsv.gz']

In [3]:
ratings_path = "../data/raw/title.ratings.tsv.gz"

ratings = pd.read_csv(
    ratings_path,
    sep="\t"
)

ratings.head()

      tconst  averageRating  numVotes
0  tt0000001            5.7      2224
1  tt0000002            5.4       323
2  tt0000003            6.4      2369
3  tt0000004            5.1       199
4  tt0000005            6.2      3080

In [4]:
ratings.shape
ratings.info()
ratings.describe()
ratings.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1704241 entries, 0 to 1704240
Data columns (total 3 columns):
 #   Column         Dtype
---  ------         -----
 0   tconst         object
 1   averageRating  float64
 2   numVotes       int64
dtypes: float64(1), int64(1), object(1)
memory usage: 39.0+ MB

tconst           0
averageRating    0
numVotes         0
dtype: int64

In [5]:
ratings["averageRating"].describe()

ratings["numVotes"].describe()

count    1.704241e+06
mean     1.033962e+03
std      1.822400e+04
min      5.000000e+00
25%      1.200000e+01
50%      2.600000e+01
75%      1.000000e+02
max      3.221305e+06
Name: numVotes, dtype: float64

## 1. Load IMDb Title Basics Dataset

In [6]:
basics_path = "../data/raw/title.basics.tsv.gz"

basics = pd.read_csv(
    basics_path,
    sep="\t",
    na_values="\\N",
    low_memory=False
)

print("Dataset loaded successfully!")
print("Shape:", basics.shape)

Dataset loaded successfully!
Shape: (12707540, 9)

In [7]:
basics.head()

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,tt0000001,short,Carmencita,Carmencita,0,1894.0,NaN,1,"Documentary,Short"
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892.0,NaN,5,"Animation,Short"
2,tt0000003,short,Poor Pierrot,Pauvre Pierrot,0,1892.0,NaN,5,"Animation,Comedy,Romance"
3,tt0000004,short,Un bon bock,Un bon bock,0,1892.0,NaN,12,"Animation,Short"
4,tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893.0,NaN,1,Short

In [8]:
basics.columns.tolist()

['tconst',
 'titleType',
 'primaryTitle',
 'originalTitle',
 'isAdult',
 'startYear',
 'endYear',
 'runtimeMinutes',
 'genres']

In [9]:
basics.info()

basics.shape

basics.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12707540 entries, 0 to 12707539
Data columns (total 9 columns):
 #   Column          Dtype
---  ------          -----
 0   tconst          object
 1   titleType       object
 2   primaryTitle    object
 3   originalTitle   object
 4   isAdult         int64
 5   startYear       float64
 6   endYear         float64
 7   runtimeMinutes  object
 8   genres          object
dtypes: float64(2), int64(1), object(6)
memory usage: 872.6+ MB

tconst                   0
titleType                0
primaryTitle            25
originalTitle           25
isAdult                  0
startYear          1478678
endYear           12547464
runtimeMinutes     8154111
genres              541036
dtype: int64

In [10]:
basics["titleType"].value_counts()

titleType
tvEpisode       9823689
short           1149337
movie            753945
video            329615
tvSeries         303466
tvMovie          155653
tvMiniSeries      72071
tvSpecial         58907
videoGame         49818
tvShort           11038
tvPilot               1
Name: count, dtype: int64

In [11]:
content_types = [
    "movie",
    "tvSeries",
    "tvMiniSeries"
]

basics_filtered = basics[
    basics["titleType"].isin(content_types)
].copy()

print("Filtered Shape:", basics_filtered.shape)

basics_filtered["titleType"].value_counts()

Filtered Shape: (1129482, 9)

titleType
movie           753945
tvSeries        303466
tvMiniSeries     72071
Name: count, dtype: int64

In [12]:
basic_columns = [
    "tconst",
    "titleType",
    "primaryTitle",
    "originalTitle",
    "isAdult",
    "startYear",
    "endYear",
    "runtimeMinutes",
    "genres"
]

basics_filtered = basics_filtered[basic_columns].copy()

basics_filtered.head()

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
8,tt0000009,movie,Miss Jerry,Miss Jerry,0,1894.0,NaN,45,Romance
144,tt0000147,movie,The Corbett-Fitzsimmons Fight,The Corbett-Fitzsimmons Fight,0,1897.0,NaN,100,"Documentary,News,Sport"
498,tt0000502,movie,Bohemios,Bohemios,0,1905.0,NaN,100,NaN
570,tt0000574,movie,The Story of the Kelly Gang,The Story of the Kelly Gang,0,1906.0,NaN,70,"Action,Adventure,Biography"
587,tt0000591,movie,The Prodigal Son,L'enfant prodigue,0,1907.0,NaN,90,Drama

In [13]:
basics_filtered.rename(
    columns={
        "tconst": "Title_ID",
        "titleType": "Content_Type",
        "primaryTitle": "Title",
        "originalTitle": "Original_Title",
        "isAdult": "Is_Adult",
        "startYear": "Release_Year",
        "endYear": "End_Year",
        "runtimeMinutes": "Runtime_Minutes",
        "genres": "Genres"
    },
    inplace=True
)

basics_filtered.columns

Index(['Title_ID', 'Content_Type', 'Title', 'Original_Title', 'Is_Adult',
       'Release_Year', 'End_Year', 'Runtime_Minutes', 'Genres'],
      dtype='object')

In [14]:
numeric_columns = [
    "Release_Year",
    "End_Year",
    "Runtime_Minutes"
]

for column in numeric_columns:
    basics_filtered[column] = pd.to_numeric(
        basics_filtered[column],
        errors="coerce"
    )

basics_filtered.dtypes

Title_ID            object
Content_Type        object
Title               object
Original_Title      object
Is_Adult             int64
Release_Year       float64
End_Year           float64
Runtime_Minutes    float64
Genres              object
dtype: object

Let's initially use 1980 onward.

In [15]:
basics_filtered = basics_filtered[
    basics_filtered["Release_Year"] >= 1980
].copy()

basics_filtered["Release_Year"].min()

np.float64(1980.0)

Remove Adult Titles

In [16]:
basics_filtered["Is_Adult"].value_counts()

basics_filtered = basics_filtered[
    basics_filtered["Is_Adult"] == 0
].copy()

basics_filtered["Is_Adult"].value_counts()

Is_Adult
0    784691
Name: count, dtype: int64

Clean Runtime (Runtime can contain missing values.)

In [17]:
basics_filtered["Runtime_Minutes"].isnull().sum()

np.int64(307411)

Clean Genres

In [21]:
basics_filtered["Genres"].head(10)

11629              Action,Crime
15477     Drama,Mystery,Romance
34792    Comedy,Fantasy,Romance
35954                 Drama,War
37406                  Thriller
46123                       NaN
47663                     Drama
56353             Drama,Fantasy
57958                     Drama
58182             Drama,Romance
Name: Genres, dtype: object

In [22]:
basics_filtered["Genres"].isnull().sum()

np.int64(55470)

Check Ratings Dataset

In [23]:
ratings

ratings.head()

ratings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1704241 entries, 0 to 1704240
Data columns (total 3 columns):
 #   Column         Dtype
---  ------         -----
 0   tconst         object
 1   averageRating  float64
 2   numVotes       int64
dtypes: float64(1), int64(1), object(1)
memory usage: 39.0+ MB

In [25]:
# Convert the numeric fields:

ratings["averageRating"] = pd.to_numeric(
    ratings["averageRating"],
    errors="coerce"
)

ratings["numVotes"] = pd.to_numeric(
    ratings["numVotes"],
    errors="coerce"
)

# Rename Rating Columns

ratings.rename(
    columns={
        "tconst": "Title_ID",
        "averageRating": "IMDb_Rating",
        "numVotes": "IMDb_Votes"
    },
    inplace=True
)

ratings.head()

    Title_ID  IMDb_Rating  IMDb_Votes
0  tt0000001          5.7        2224
1  tt0000002          5.4         323
2  tt0000003          6.4        2369
3  tt0000004          5.1         199
4  tt0000005          6.2        3080

In [27]:
# Check Duplicate IDs
# Before merging, check whether Title_ID is unique.

print(
    "Duplicate Title IDs:",
    ratings["Title_ID"].duplicated().sum()
)

# Do the same for our basics data:

print(
    "Duplicate Title IDs:",
    basics_filtered["Title_ID"].duplicated().sum()
)

Duplicate Title IDs: 0
Duplicate Title IDs: 0

# Merge the Two Datasets 🔗

In [28]:
df = basics_filtered.merge(
    ratings,
    on="Title_ID",
    how="inner"
)

print("Final merged shape:", df.shape)

df.head()

Final merged shape: (395468, 11)

,Title_ID,Content_Type,Title,Original_Title,Is_Adult,Release_Year,End_Year,Runtime_Minutes,Genres,IMDb_Rating,IMDb_Votes
0,tt0015724,movie,Dama de noche,Dama de noche,0,1993.0,NaN,102.0,"Drama,Mystery,Romance",6.2,35
1,tt0035423,movie,Kate & Leopold,Kate & Leopold,0,2001.0,NaN,118.0,"Comedy,Fantasy,Romance",6.4,94417
2,tt0036606,movie,"Another Time, Another Place","Another Time, Another Place",0,1983.0,NaN,118.0,"Drama,War",6.4,386
3,tt0038086,movie,Shiva und die Galgenblume,Shiva und die Galgenblume,0,1993.0,NaN,NaN,Thriller,7.0,26
4,tt0048550,movie,Rendez-vous of the Docks,Le rendez-vous des quais,0,1990.0,NaN,75.0,Drama,6.5,75

Apply Rating Quality Filter

In [29]:
df_analysis = df[
    df["IMDb_Votes"] >= 100
].copy()

print("Before filter:", df.shape)
print("After filter:", df_analysis.shape)

Before filter: (395468, 11)
After filter: (156380, 11)

Check Rating Range

In [30]:
df_analysis["IMDb_Rating"].describe()

print(
    "Minimum Rating:",
    df_analysis["IMDb_Rating"].min()
)

print(
    "Maximum Rating:",
    df_analysis["IMDb_Rating"].max()
)

print(
    "Average Rating:",
    df_analysis["IMDb_Rating"].mean()
)

Minimum Rating: 1.0
Maximum Rating: 9.9
Average Rating: 6.098286865328047

Check Release Years

In [31]:
df_analysis["Release_Year"].describe()

df_analysis["Release_Year"].min()
df_analysis["Release_Year"].max()

np.float64(2026.0)

Check Content Distribution

In [32]:
df_analysis["Content_Type"].value_counts()

content_distribution = (
    df_analysis["Content_Type"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

content_distribution

Content_Type
movie           74.01
tvSeries        20.92
tvMiniSeries     5.07
Name: proportion, dtype: float64

In [33]:
# Creating Rating Category

def rating_category(rating):
    if rating >= 9:
        return "Masterpiece"
    elif rating >= 8:
        return "Excellent"
    elif rating >= 7:
        return "Good"
    elif rating >= 6:
        return "Average"
    else:
        return "Low Rated"

df_analysis["Rating_Category"] = (
    df_analysis["IMDb_Rating"]
    .apply(rating_category)
)

df_analysis["Rating_Category"].value_counts()

Rating_Category
Low Rated      63337
Average        47590
Good           34824
Excellent       9803
Masterpiece      826
Name: count, dtype: int64

In [34]:
# Create Decade Column

df_analysis["Decade"] = (
    (df_analysis["Release_Year"] // 10) * 10
)

df_analysis[
    ["Title", "Release_Year", "Decade"]
].head(10)

                                                Title  Release_Year  Decade
1                                      Kate & Leopold        2001.0  2000.0
2                         Another Time, Another Place        1983.0  1980.0
7                                         Born in '45        1990.0  1990.0
9                                           Hands Up!        1981.0  1980.0
10  The Tango of the Widower and Its Distorting Mi...        2020.0  2020.0
11                                        Zeg 'ns Aaa        1981.0  1980.0
17                                        Lucky Seven        1986.0  1980.0
18                                    Ninja Destroyer        1986.0  1980.0
19                                        Firecracker        1981.0  1980.0
21                                  Trial on the Road        1986.0  1980.0

In [35]:
# Create Popularity Category

def popularity_category(votes):
    if votes >= 100000:
        return "Very High"
    elif votes >= 10000:
        return "High"
    elif votes >= 1000:
        return "Medium"
    else:
        return "Low"

df_analysis["Popularity_Category"] = (
    df_analysis["IMDb_Votes"]
    .apply(popularity_category)
)

df_analysis["Popularity_Category"].value_counts()

Popularity_Category
Low          103713
Medium        38802
High          10938
Very High      2927
Name: count, dtype: int64

In [36]:
df_analysis.info()

df_analysis.isnull().sum()

df_analysis.head()

<class 'pandas.core.frame.DataFrame'>
Index: 156380 entries, 1 to 395463
Data columns (total 14 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Title_ID             156380 non-null  object
 1   Content_Type         156380 non-null  object
 2   Title                156380 non-null  object
 3   Original_Title       156380 non-null  object
 4   Is_Adult             156380 non-null  int64
 5   Release_Year         156380 non-null  float64
 6   End_Year             28193 non-null   float64
 7   Runtime_Minutes      141177 non-null  float64
 8   Genres               155867 non-null  object
 9   IMDb_Rating          156380 non-null  float64
 10  IMDb_Votes           156380 non-null  int64
 11  Rating_Category      156380 non-null  object
 12  Decade               156380 non-null  float64
 13  Popularity_Category  156380 non-null  object
dtypes: float64(5), int64(2), object(7)
memory usage: 17.9+ MB

,Title_ID,Content_Type,Title,Original_Title,Is_Adult,Release_Year,End_Year,Runtime_Minutes,Genres,IMDb_Rating,IMDb_Votes,Rating_Category,Decade,Popularity_Category
1,tt0035423,movie,Kate & Leopold,Kate & Leopold,0,2001.0,NaN,118.0,"Comedy,Fantasy,Romance",6.4,94417,Average,2000.0,High
2,tt0036606,movie,"Another Time, Another Place","Another Time, Another Place",0,1983.0,NaN,118.0,"Drama,War",6.4,386,Average,1980.0,Low
7,tt0059325,movie,Born in '45,Jahrgang 45,0,1990.0,NaN,94.0,"Drama,Romance",6.5,297,Average,1990.0,Low
9,tt0062181,movie,Hands Up!,Rece do góry,0,1981.0,NaN,80.0,Drama,6.5,513,Average,1980.0,Low
10,tt0062336,movie,The Tango of the Widower and Its Distorting Mi...,El tango del viudo y su espejo deformante,0,2020.0,NaN,70.0,"Drama,Mystery",6.3,297,Average,2020.0,Low

In [37]:
# Sort the DataFrame by IMDb_Rating and IMDb_Votes in descending order, and select the top 20 entries.

top_rated = (
    df_analysis
    .sort_values(
        by=["IMDb_Rating", "IMDb_Votes"],
        ascending=[False, False]
    )
    .head(20)
)

top_rated[
    [
        "Title",
        "Content_Type",
        "Release_Year",
        "Genres",
        "IMDb_Rating",
        "IMDb_Votes"
    ]
]

,Title,Content_Type,Release_Year,Genres,IMDb_Rating,IMDb_Votes
309775,Lyonheart Universe,tvMiniSeries,2025.0,"Action,Sci-Fi,Thriller",9.9,903
319801,Yaar Jigree Kasooti Degree,movie,2026.0,Drama,9.9,623
322481,Raithara Makkalige Hennu Kodi,movie,2026.0,Family,9.9,105
316697,Trap Father,tvSeries,2026.0,Drama,9.8,547
287353,Borderline Forever,movie,2021.0,"Adventure,Comedy,Fantasy",9.8,142
295165,Out the Game,movie,2025.0,Thriller,9.8,136
230423,OdBita Pot,tvSeries,2022.0,Adventure,9.7,1348
308882,Boss,movie,2026.0,"Crime,Thriller",9.7,558
292495,From China with Love,movie,2025.0,"Crime,Drama,Thriller",9.7,549
316831,Get Set Go,movie,2026.0,"Action,Thriller",9.7,243
357258,Steven Reeds Weber Cooks,tvMiniSeries,2012.0,Drama,9.7,218
56700,Illusory Thoughts,movie,1989.0,"Documentary,Drama,Music",9.7,152
217416,Twenty One Pilots: Cinema Experience Extended Cut,movie,2022.0,Music,9.7,146
142694,The Story of Your Life,movie,2008.0,"Drama,Romance,Thriller",9.7,142
181030,Fishmans: Otokotachi no Wakare 98.12.28 @ Akas...,movie,2005.0,Music,9.7,112
251148,Come pesci nell'acqua,movie,2024.0,Documentary,9.7,100
365329,Choufli Hal,tvSeries,2005.0,Comedy,9.6,3404
322515,Oka Court Case,movie,2026.0,Drama,9.6,2010
344357,Kothao Keu Nei,tvMiniSeries,1990.0,"Crime,Drama",9.6,1545
310690,The Great Punjab Robbery,movie,2026.0,Thriller,9.6,1512

In [38]:
# Save the processed dataset to a CSV file in the "data/processed" directory.

import os

os.makedirs("../data/processed", exist_ok=True)

output_path = "../data/processed/imdb_movies_ratings.csv"

df_analysis.to_csv(
    output_path,
    index=False
)

print("Dataset saved successfully!")
print(output_path)

Dataset saved successfully!
../data/processed/imdb_movies_ratings.csv

In [39]:
# Verify the saved file

import os
import pandas as pd

file_size = os.path.getsize(output_path) / (1024 * 1024)

print(f"File size: {file_size:.2f} MB")

final_df = pd.read_csv(output_path)

print("Rows:", len(final_df))
print("Columns:", len(final_df.columns))

File size: 16.97 MB
Rows: 156380
Columns: 14

In [40]:
print("Rows:", len(final_df))
print("Columns:", len(final_df.columns))

Rows: 156380
Columns: 14